### ISSUE TITLE
v2 tasklist/roadmap

### ISSUE THREAD

**Issue by rahul286** [rtCamp/media-node#18]
We never released or better say tagged v1 to be specific but I have decided to work on media-node from scratch. Following tasks we need to accomplish, mostly in order.
# Video Encoding 
- [ ] Run `ffmpeg` with higher quality. Last time in favor of low quality devices, we choose to reduce quality. This time we will start with higher quality which I hopefully will serve much bigger audience. We will refer to - https://blog.mediacru.sh/2013/12/23/The-right-way-to-encode-HTML5-video.html
- [ ] Support for 3 video formats. Again we will refer to - https://blog.mediacru.sh/2013/12/23/The-right-way-to-encode-HTML5-video.html and we will try to use https://github.com/typeoneerror-studios/node-html5video
- [ ] Support for different bandwidth for each format. i.e. ability to turn on/off HD. Problem with this approach is - we are yet to find a video player which supports multiple video formats with multiple bitrates.
- [ ] rotation handling - https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/issues/327#issuecomment-57452716
# Audio Encoding 
- [ ] mp3 and ogg support as per - https://blog.mediacru.sh/2013/12/23/The-right-way-to-encode-HTML5-video.html
# Packaging
- [ ] npm package called `media-node` based on https://github.com/fluent-ffmpeg/node-fluent-ffmpeg
- [ ] REST API with v1 endpoints for backward compatibility
